name: datadog_inappwebview_tracking
description: "A package for tracking Datadog sessions in webviews create with flutter_inappwebview"
version: 1.0.0
homepage: https://datadoghq.com
repository: https://github.com/DataDog/dd-sdk-flutter

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  datadog_flutter_plugin: ^2.10.0
  plugin_platform_interface: ^2.0.2
  flutter_inappwebview: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  datadog_common_test:
    path: ../datadog_common_test

flutter:
  plugin:
    platforms:
      android:
        package: com.datadoghq.flutter.inappwebviewtracking
        pluginClass: DatadogInAppWebViewTrackingPlugin
      ios:
        pluginClass: DatadogInAppWebViewTrackingPlugin
